Sandwich-Way/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sandwich_Way.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sandwich-Way/Controllers/SandwichController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Sandwich_Way.Models;
using Sandwich_Way.ViewModels;

namespace Sandwich_Way.Controllers
{
    public class SandwichController : Controller
    {
        private readonly ISandwichRepository _sandwichRepository;
        private readonly ICategoryRepository _categoryRepository;

        public SandwichController(ISandwichRepository sandwichRepository, ICategoryRepository categoryRepository)
        {
            _sandwichRepository = sandwichRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult List(string category)
        {
            IEnumerable<Sandwiches> sandwiches;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                sandwiches = _sandwichRepository.GetAllSandwiches.OrderBy(s => s.SandwichId);
                currentCategory = "All Candy";
            }

            else
            {
                sandwiches = _sandwichRepository.GetAllSandwiches.Where(c => c.Category.CategoryName == category);

                currentCategory = _categoryRepository.GetAllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new SandwichListViewModel
            {
                Sandwiches = sandwiches,
                CurrentCategory = currentCategory
            });

        }

        public IActionResult Details(int id)
        {
            var sandwich = _sandwichRepository.GetSandwichesById(id);
            if (sandwich == null)
                return NotFound();

            return View(sandwich);
        }
    }
}

Sandwich-Way/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using Sandwich_Way.Models;
using Sandwich_Way.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sandwich_Way.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ISandwichRepository _sandwichRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(ISandwichRepository sandwichRepository, ShoppingCart shoppingCart)
        {
            _sandwichRepository = sandwichRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            _shoppingCart.ShoppingCartItems = _shoppingCart.GetShoppingCartItems();

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int sandwichId)
        {
            var selectedSandwich = _sandwichRepository.GetAllSandwiches.FirstOrDefault(s => s.SandwichId == sandwichId);

            if (selectedSandwich != null)
            {
                _shoppingCart.AddToCart(selectedSandwich, 1);
            }

            return RedirectToAction("Index");

        }

        public RedirectToActionResult RemoveFromShoppingCart(int sandwichId)
        {
            var selectedSandwich = _sandwichRepository.GetAllSandwiches.FirstOrDefault(s => s.SandwichId == sandwichId);

            if (selectedSandwich != null)
            {
                _shoppingCart.RemoveFromCart(selectedSandwich);
            }

            return RedirectToAction("Index");

        }
    }
}

Sandwich-Way/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

Sandwich-Way/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/content/site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        @await Component.InvokeAsync("CategoryMenu")
                        <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                        @await Component.InvokeAsync("ShoppingCartSummary")
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" src="~/Images/Sandwich-way.jpg" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>

Sandwich-Way/Views/Shared/_sandwichCard.cshtml
@model Sandwiches

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="image for sandwiches" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3><a asp-controller="Sandwich" asp-action="Details" asp-route-id="@Model.SandwichId">@Model.SandwichName</a></h3>
            <p>@Model.Description</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-sandwichId="@Model.SandwichId">Add to Cart</a>
            </p>
        </div>
    </div>
</div>